name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'metadata.txt'
      - '**.py'
  create:
    tags:
      - 'v*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci
        
      - name: Validate Metadata
        run: qgis-plugin-ci validate

  release:
    needs: validate
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci
        
      - name: Release and Deploy
        run: |
            qgis-plugin-ci release \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --create-plugin-repo \
            --osgeo-username ${{ secrets.OSGEO_USERNAME }} \
            --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Nota: As credenciais OSGEO são opcionais se não for publicar no repositório oficial agora.
        # O parametro --create-plugin-repo cria o XML para gh-pages.
